/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sqs.queues;
//package sqs;
import com.amazonaws.services.sqs.AmazonSQS;
import com.amazonaws.services.sqs.AmazonSQSClientBuilder;
import com.amazonaws.services.sqs.model.AmazonSQSException;
import com.amazonaws.services.sqs.model.CreateQueueResult;
import com.amazonaws.services.sqs.model.Message;
import com.amazonaws.services.sqs.model.SendMessageBatchRequest;
import com.amazonaws.services.sqs.model.SendMessageBatchRequestEntry;
import com.amazonaws.services.sqs.model.SendMessageRequest;
import java.util.Date;
import java.util.List;

public class Subscriber {
    private static final String QUEUE_NAMEA = "QueueA" ;
    private static final String QUEUE_NAMEB = "QueueB" ;
    private static final String QUEUE_NAMEC = "QueueC" ;

    public static void main(String[] args){
        final AmazonSQS sqs = AmazonSQSClientBuilder.defaultClient();

        String queueUrl = sqs.getQueueUrl(QUEUE_NAMEA).getQueueUrl();
        List<Message> messages = sqs.receiveMessage(queueUrl).getMessages();

        for (Message m : messages) {
            System.out.println(m);
        }
//        for (Message m : messages) {
//            sqs.deleteMessage(queueUrl, m.getReceiptHandle());
//        }
    }
}
